#! /bin/sh
# /etc/init.d/opr-server

### BEGIN INIT INFO
# Provides:          opr-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OPR Server initscript
### END INIT INFO

case "$1" in
   start)
    echo "Starting opr-server"
    /usr/bin/node /home/pi/services/opr-server/index.js >> /home/pi/services/opr-server/opr-server.log &
   ;;
   stop)
    echo "Stopping opr-server"
    killall -9 node
    ;;
  *)
    echo "Usage: /etc/init.d/opr-server {start|stop}"
    exit 1
    ;;
esac

exit 0
